In [1]:
import pandas as pd

In [2]:
df_original = pd.read_csv("../datos/madrid_4_2025.csv", parse_dates = True, sep = ";")
df_original.head()

,provincia,municipio,estacion,magnitud,punto_muestreo,ano,mes,dia,h01,v01,...,h20,v20,h21,v21,h22,v22,h23,v23,h24,v24
0,28,102,1,1,28102001_1_38,2025,4,1,4,V,...,4,V,4,V,4,V,4,V,4,V
1,28,102,1,6,28102001_6_48,2025,4,1,"0,3",V,...,"0,3",V,"0,3",V,"0,3",V,"0,3",V,"0,3",V
2,28,102,1,7,28102001_7_8,2025,4,1,1,V,...,1,V,1,V,1,V,1,V,1,V
3,28,102,1,8,28102001_8_8,2025,4,1,4,V,...,6,V,3,V,2,V,3,V,3,V
4,28,102,1,10,28102001_10_49,2025,4,1,9,V,...,9,V,8,V,8,V,7,V,8,V

In [3]:
df_pruebas = df_original[["punto_muestreo", "ano", "mes", "dia", "h01", "v01", "h02", "v02", "h03", "v03","h04", "v04"]]
df_pruebas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 362 entries, 0 to 361
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   punto_muestreo  362 non-null    object
 1   ano             362 non-null    int64
 2   mes             362 non-null    int64
 3   dia             362 non-null    int64
 4   h01             362 non-null    object
 5   v01             362 non-null    object
 6   h02             362 non-null    object
 7   v02             362 non-null    object
 8   h03             362 non-null    object
 9   v03             362 non-null    object
 10  h04             362 non-null    object
 11  v04             362 non-null    object
dtypes: int64(3), object(9)
memory usage: 34.1+ KB

In [4]:
df_pruebas[["ano", "mes", "dia"]] = (df_pruebas[["ano", "mes", "dia"]]).astype(str)

C:\Users\marta\AppData\Local\Temp\ipykernel_4668\2820210921.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pruebas[["ano", "mes", "dia"]] = (df_pruebas[["ano", "mes", "dia"]]).astype(str)

In [5]:
df_pruebas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 362 entries, 0 to 361
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   punto_muestreo  362 non-null    object
 1   ano             362 non-null    object
 2   mes             362 non-null    object
 3   dia             362 non-null    object
 4   h01             362 non-null    object
 5   v01             362 non-null    object
 6   h02             362 non-null    object
 7   v02             362 non-null    object
 8   h03             362 non-null    object
 9   v03             362 non-null    object
 10  h04             362 non-null    object
 11  v04             362 non-null    object
dtypes: object(12)
memory usage: 34.1+ KB

In [6]:
df_pruebas["fecha"] = df_pruebas["ano"] + "-" + df_pruebas["mes"] + "-" + df_pruebas["dia"]
df_pruebas.drop(columns = ["ano", "mes", "dia"], inplace=True)
df_pruebas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 362 entries, 0 to 361
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   punto_muestreo  362 non-null    object
 1   h01             362 non-null    object
 2   v01             362 non-null    object
 3   h02             362 non-null    object
 4   v02             362 non-null    object
 5   h03             362 non-null    object
 6   v03             362 non-null    object
 7   h04             362 non-null    object
 8   v04             362 non-null    object
 9   fecha           362 non-null    object
dtypes: object(10)
memory usage: 28.4+ KB

C:\Users\marta\AppData\Local\Temp\ipykernel_4668\2063085378.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pruebas["fecha"] = df_pruebas["ano"] + "-" + df_pruebas["mes"] + "-" + df_pruebas["dia"]
C:\Users\marta\AppData\Local\Temp\ipykernel_4668\2063085378.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pruebas.drop(columns = ["ano", "mes", "dia"], inplace=True)

In [7]:
df_pruebas

     punto_muestreo  h01 v01  h02 v02  h03 v03  h04 v04     fecha
0     28102001_1_38    4   V    4   V    4   V    4   V  2025-4-1
1     28102001_6_48  0,3   V  0,3   V  0,3   V  0,2   V  2025-4-1
2      28102001_7_8    1   V    1   V    1   V    1   V  2025-4-1
3      28102001_8_8    4   V    5   V    4   V    3   V  2025-4-1
4    28102001_10_49    9   V    6   V    6   V    6   V  2025-4-1
..              ...  ...  ..  ...  ..  ...  ..  ...  ..       ...
357    28092005_7_8    2   V    2   V    2   V    2   V  2025-4-2
358    28092005_8_8    4   V    4   V    5   V    7   V  2025-4-2
359  28092005_10_49   17   V   15   V   14   V   13   V  2025-4-2
360   28092005_12_8    7   V    7   V    8   V   10   V  2025-4-2
361   28092005_14_6   82   V   77   V   71   V   66   V  2025-4-2

[362 rows x 10 columns]

In [8]:
df_pruebas_peque = df_pruebas[df_pruebas["punto_muestreo"].str.startswith("28102001")]
df_pruebas_peque

     punto_muestreo  h01 v01  h02 v02  h03 v03  h04 v04     fecha
0     28102001_1_38    4   V    4   V    4   V    4   V  2025-4-1
1     28102001_6_48  0,3   V  0,3   V  0,3   V  0,2   V  2025-4-1
2      28102001_7_8    1   V    1   V    1   V    1   V  2025-4-1
3      28102001_8_8    4   V    5   V    4   V    3   V  2025-4-1
4    28102001_10_49    9   V    6   V    6   V    6   V  2025-4-1
5     28102001_12_8    6   V    7   V    6   V    5   V  2025-4-1
6     28102001_14_6   94   V   82   V   80   V   73   V  2025-4-1
181   28102001_1_38    4   V    4   V    4   V    4   V  2025-4-2
182   28102001_6_48  0,3   V  0,3   V  0,3   V  0,3   V  2025-4-2
183    28102001_7_8    1   V    1   V    1   V    1   V  2025-4-2
184    28102001_8_8    3   V    2   V    2   V    2   V  2025-4-2
185  28102001_10_49    9   V   10   V   10   V   11   V  2025-4-2
186   28102001_12_8    5   V    4   V    4   V    4   V  2025-4-2
187   28102001_14_6   76   V   74   V   70   V   65   V  2025-4-2

In [3]:
def combinar_h_v(df):
    """
    Combina pares de columnas que empiezan por 'h' y 'v' en un DataFrame,
    creando nuevas columnas con los valores combinados. AdemÃ¡s, devuelve
    una lista de las columnas creadas.

    Args:
        df (pd.DataFrame): DataFrame original.

    Returns:
        pd.DataFrame: DataFrame con columnas combinadas aÃ±adidas.
        list: Lista de nombres de las columnas creadas.
    """
    columnas_h = [col for col in df.columns if col.startswith('h')]
    columnas_v = [col for col in df.columns if col.startswith('v')]
    
    columnas_creadas = []  # Lista para almacenar nombres de las columnas creadas

    for col_h, col_v in zip(columnas_h, columnas_v):
        nueva_columna = f"{col_h}_{col_v}"  # Nombre de la nueva columna
        df[nueva_columna] = df[col_h].astype(str) + " " + df[col_v].astype(str)
        columnas_creadas.append(nueva_columna)  # Agregar el nombre de la columna a la lista
    
    return df, columnas_creadas

In [10]:
df_pruebas_peque, columnas_creadas = combinar_h_v(df_pruebas_peque)
df_pruebas_peque

C:\Users\marta\AppData\Local\Temp\ipykernel_4668\3637698816.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[nueva_columna] = df[col_h].astype(str) + " " + df[col_v].astype(str)
C:\Users\marta\AppData\Local\Temp\ipykernel_4668\3637698816.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[nueva_columna] = df[col_h].astype(str) + " " + df[col_v].astype(str)
C:\Users\marta\AppData\Local\Temp\ipykernel_4668\3637698816.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[nueva_columna] = df[col_h].astype(str) + " " + df[col_v].astype(str)
C:\Users\marta\AppData\Local\Temp\ipykernel_4668\3637698816.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[nueva_columna] = df[col_h].astype(str) + " " + df[col_v].astype(str)

,punto_muestreo,h01,v01,h02,v02,h03,v03,h04,v04,fecha,h01_v01,h02_v02,h03_v03,h04_v04
0,28102001_1_38,4,V,4,V,4,V,4,V,2025-4-1,4 V,4 V,4 V,4 V
1,28102001_6_48,"0,3",V,"0,3",V,"0,3",V,"0,2",V,2025-4-1,"0,3 V","0,3 V","0,3 V","0,2 V"
2,28102001_7_8,1,V,1,V,1,V,1,V,2025-4-1,1 V,1 V,1 V,1 V
3,28102001_8_8,4,V,5,V,4,V,3,V,2025-4-1,4 V,5 V,4 V,3 V
4,28102001_10_49,9,V,6,V,6,V,6,V,2025-4-1,9 V,6 V,6 V,6 V
5,28102001_12_8,6,V,7,V,6,V,5,V,2025-4-1,6 V,7 V,6 V,5 V
6,28102001_14_6,94,V,82,V,80,V,73,V,2025-4-1,94 V,82 V,80 V,73 V
181,28102001_1_38,4,V,4,V,4,V,4,V,2025-4-2,4 V,4 V,4 V,4 V
182,28102001_6_48,"0,3",V,"0,3",V,"0,3",V,"0,3",V,2025-4-2,"0,3 V","0,3 V","0,3 V","0,3 V"
183,28102001_7_8,1,V,1,V,1,V,1,V,2025-4-2,1 V,1 V,1 V,1 V
184,28102001_8_8,3,V,2,V,2,V,2,V,2025-4-2,3 V,2 V,2 V,2 V
185,28102001_10_49,9,V,10,V,10,V,11,V,2025-4-2,9 V,10 V,10 V,11 V
186,28102001_12_8,5,V,4,V,4,V,4,V,2025-4-2,5 V,4 V,4 V,4 V
187,28102001_14_6,76,V,74,V,70,V,65,V,2025-4-2,76 V,74 V,70 V,65 V

In [11]:
# quiero probar a unir el valor de h con el valor de v para hacer el melt y luego separarlo
df_horas = df_pruebas_peque.melt(
    id_vars=["punto_muestreo", "fecha"],  # Columnas que no se transforman
    value_vars=columnas_creadas,  # Columnas de horas que queremos transformar
    var_name="hora",  # Nombre de la nueva columna que contiene las etiquetas de hora
    value_name="valor"  # Nombre de la nueva columna que contiene los valores
)

In [12]:
df_horas = df_pruebas_peque.melt(
    id_vars=["punto_muestreo", "fecha"],  # Columnas que no se transforman
    value_vars=["h01_v01", "h02_v02", "h03_v03", "h04_v04"],  # Columnas de horas que queremos transformar
    var_name="hora",  # Nombre de la nueva columna que contiene las etiquetas de hora
    value_name="valor"  # Nombre de la nueva columna que contiene los valores
)

In [13]:
df_horas.sort_values(by = ["punto_muestreo", "fecha", "hora"], inplace=True)
df_horas

    punto_muestreo     fecha     hora  valor
4   28102001_10_49  2025-4-1  h01_v01    9 V
18  28102001_10_49  2025-4-1  h02_v02    6 V
32  28102001_10_49  2025-4-1  h03_v03    6 V
46  28102001_10_49  2025-4-1  h04_v04    6 V
11  28102001_10_49  2025-4-2  h01_v01    9 V
25  28102001_10_49  2025-4-2  h02_v02   10 V
39  28102001_10_49  2025-4-2  h03_v03   10 V
53  28102001_10_49  2025-4-2  h04_v04   11 V
5    28102001_12_8  2025-4-1  h01_v01    6 V
19   28102001_12_8  2025-4-1  h02_v02    7 V
33   28102001_12_8  2025-4-1  h03_v03    6 V
47   28102001_12_8  2025-4-1  h04_v04    5 V
12   28102001_12_8  2025-4-2  h01_v01    5 V
26   28102001_12_8  2025-4-2  h02_v02    4 V
40   28102001_12_8  2025-4-2  h03_v03    4 V
54   28102001_12_8  2025-4-2  h04_v04    4 V
6    28102001_14_6  2025-4-1  h01_v01   94 V
20   28102001_14_6  2025-4-1  h02_v02   82 V
34   28102001_14_6  2025-4-1  h03_v03   80 V
48   28102001_14_6  2025-4-1  h04_v04   73 V
13   28102001_14_6  2025-4-2  h01_v01   76 V
27   28102001_14_6  2025-4-2  h02_v02   74 V
41   28102001_14_6  2025-4-2  h03_v03   70 V
55   28102001_14_6  2025-4-2  h04_v04   65 V
0    28102001_1_38  2025-4-1  h01_v01    4 V
14   28102001_1_38  2025-4-1  h02_v02    4 V
28   28102001_1_38  2025-4-1  h03_v03    4 V
42   28102001_1_38  2025-4-1  h04_v04    4 V
7    28102001_1_38  2025-4-2  h01_v01    4 V
21   28102001_1_38  2025-4-2  h02_v02    4 V
35   28102001_1_38  2025-4-2  h03_v03    4 V
49   28102001_1_38  2025-4-2  h04_v04    4 V
1    28102001_6_48  2025-4-1  h01_v01  0,3 V
15   28102001_6_48  2025-4-1  h02_v02  0,3 V
29   28102001_6_48  2025-4-1  h03_v03  0,3 V
43   28102001_6_48  2025-4-1  h04_v04  0,2 V
8    28102001_6_48  2025-4-2  h01_v01  0,3 V
22   28102001_6_48  2025-4-2  h02_v02  0,3 V
36   28102001_6_48  2025-4-2  h03_v03  0,3 V
50   28102001_6_48  2025-4-2  h04_v04  0,3 V
2     28102001_7_8  2025-4-1  h01_v01    1 V
16    28102001_7_8  2025-4-1  h02_v02    1 V
30    28102001_7_8  2025-4-1  h03_v03    1 V
44    28102001_7_8  2025-4-1  h04_v04    1 V
9     28102001_7_8  2025-4-2  h01_v01    1 V
23    28102001_7_8  2025-4-2  h02_v02    1 V
37    28102001_7_8  2025-4-2  h03_v03    1 V
51    28102001_7_8  2025-4-2  h04_v04    1 V
3     28102001_8_8  2025-4-1  h01_v01    4 V
17    28102001_8_8  2025-4-1  h02_v02    5 V
31    28102001_8_8  2025-4-1  h03_v03    4 V
45    28102001_8_8  2025-4-1  h04_v04    3 V
10    28102001_8_8  2025-4-2  h01_v01    3 V
24    28102001_8_8  2025-4-2  h02_v02    2 V
38    28102001_8_8  2025-4-2  h03_v03    2 V
52    28102001_8_8  2025-4-2  h04_v04    2 V

In [14]:
# ahora separamos la letra que acompaÃ±a al valor para crear la columna de validaciÃ³n y dejamos solo la hora en la columna hora
df_horas["hora"] = df_horas["hora"].str.split("_", expand = True)[0]
df_horas["validacion"] = df_horas["valor"].str.split(" ", expand = True)[1]
df_horas["valor"] = df_horas["valor"].str.split(" ", expand = True)[0]
df_horas["id_medida"] = df_horas["punto_muestreo"] + "_" + df_horas["fecha"] + "_" + df_horas["hora"] + "_" + df_horas["validacion"]
df_horas.drop(columns=["punto_muestreo", "fecha", "hora", "validacion"], inplace=True)
df_horas

   valor                      id_medida
4      9  28102001_10_49_2025-4-1_h01_V
18     6  28102001_10_49_2025-4-1_h02_V
32     6  28102001_10_49_2025-4-1_h03_V
46     6  28102001_10_49_2025-4-1_h04_V
11     9  28102001_10_49_2025-4-2_h01_V
25    10  28102001_10_49_2025-4-2_h02_V
39    10  28102001_10_49_2025-4-2_h03_V
53    11  28102001_10_49_2025-4-2_h04_V
5      6   28102001_12_8_2025-4-1_h01_V
19     7   28102001_12_8_2025-4-1_h02_V
33     6   28102001_12_8_2025-4-1_h03_V
47     5   28102001_12_8_2025-4-1_h04_V
12     5   28102001_12_8_2025-4-2_h01_V
26     4   28102001_12_8_2025-4-2_h02_V
40     4   28102001_12_8_2025-4-2_h03_V
54     4   28102001_12_8_2025-4-2_h04_V
6     94   28102001_14_6_2025-4-1_h01_V
20    82   28102001_14_6_2025-4-1_h02_V
34    80   28102001_14_6_2025-4-1_h03_V
48    73   28102001_14_6_2025-4-1_h04_V
13    76   28102001_14_6_2025-4-2_h01_V
27    74   28102001_14_6_2025-4-2_h02_V
41    70   28102001_14_6_2025-4-2_h03_V
55    65   28102001_14_6_2025-4-2_h04_V
0      4   28102001_1_38_2025-4-1_h01_V
14     4   28102001_1_38_2025-4-1_h02_V
28     4   28102001_1_38_2025-4-1_h03_V
42     4   28102001_1_38_2025-4-1_h04_V
7      4   28102001_1_38_2025-4-2_h01_V
21     4   28102001_1_38_2025-4-2_h02_V
35     4   28102001_1_38_2025-4-2_h03_V
49     4   28102001_1_38_2025-4-2_h04_V
1    0,3   28102001_6_48_2025-4-1_h01_V
15   0,3   28102001_6_48_2025-4-1_h02_V
29   0,3   28102001_6_48_2025-4-1_h03_V
43   0,2   28102001_6_48_2025-4-1_h04_V
8    0,3   28102001_6_48_2025-4-2_h01_V
22   0,3   28102001_6_48_2025-4-2_h02_V
36   0,3   28102001_6_48_2025-4-2_h03_V
50   0,3   28102001_6_48_2025-4-2_h04_V
2      1    28102001_7_8_2025-4-1_h01_V
16     1    28102001_7_8_2025-4-1_h02_V
30     1    28102001_7_8_2025-4-1_h03_V
44     1    28102001_7_8_2025-4-1_h04_V
9      1    28102001_7_8_2025-4-2_h01_V
23     1    28102001_7_8_2025-4-2_h02_V
37     1    28102001_7_8_2025-4-2_h03_V
51     1    28102001_7_8_2025-4-2_h04_V
3      4    28102001_8_8_2025-4-1_h01_V
17     5    28102001_8_8_2025-4-1_h02_V
31     4    28102001_8_8_2025-4-1_h03_V
45     3    28102001_8_8_2025-4-1_h04_V
10     3    28102001_8_8_2025-4-2_h01_V
24     2    28102001_8_8_2025-4-2_h02_V
38     2    28102001_8_8_2025-4-2_h03_V
52     2    28102001_8_8_2025-4-2_h04_V

In [15]:
# ahora aplicamos todo al df grande
def formato_df(df):
    df[["ano", "mes", "dia"]] = (df[["ano", "mes", "dia"]]).astype(str)
    df["fecha"] = df["ano"] + "-" + df["mes"] + "-" + df["dia"]
    #df_pruebas.drop(columns = ["ano", "mes", "dia"], inplace=True)  
    df, columnas_creadas = combinar_h_v(df)
    print(columnas_creadas)
    df = df.melt(
        id_vars=["provincia", "municipio", "estacion", "magnitud", "punto_muestreo", "fecha"],  # Columnas que no se transforman
        value_vars=columnas_creadas,  # Columnas de horas que queremos transformar
        var_name="hora",  # Nombre de la nueva columna que contiene las etiquetas de hora
        value_name="valor"  # Nombre de la nueva columna que contiene los valores
        )
    # ahora separamos la letra que acompaÃ±a al valor para crear la columna de validaciÃ³n y dejamos solo la hora en la columna hora
    df["hora"] = df["hora"].str.split("_", expand = True)[0]
    df["validacion"] = df["valor"].str.split(" ", expand = True)[1]
    df["valor"] = df["valor"].str.split(" ", expand = True)[0]
    df["id_medida"] = df["punto_muestreo"] + "_" + df["fecha"] + "_" + df["hora"] + "_" + df["validacion"]
    #df.drop(columns=["punto_muestreo", "fecha", "hora", "validacion"], inplace=True)
    return df

In [16]:
df_original.head()

,provincia,municipio,estacion,magnitud,punto_muestreo,ano,mes,dia,h01,v01,...,h15_v15,h16_v16,h17_v17,h18_v18,h19_v19,h20_v20,h21_v21,h22_v22,h23_v23,h24_v24
0,28,102,1,1,28102001_1_38,2025,4,1,4,V,...,5 V,5 V,5 V,5 V,4 V,4 V,4 V,4 V,4 V,4 V
1,28,102,1,6,28102001_6_48,2025,4,1,"0,3",V,...,"0,2 V","0,3 V","0,2 V","0,3 V","0,3 V","0,3 V","0,3 V","0,3 V","0,3 V","0,3 V"
2,28,102,1,7,28102001_7_8,2025,4,1,1,V,...,1 V,1 V,1 V,1 V,1 V,1 V,1 V,1 V,1 V,1 V
3,28,102,1,8,28102001_8_8,2025,4,1,4,V,...,6 V,5 V,4 V,4 V,3 V,6 V,3 V,2 V,3 V,3 V
4,28,102,1,10,28102001_10_49,2025,4,1,9,V,...,9 V,11 V,12 V,12 V,11 V,9 V,8 V,8 V,7 V,8 V

In [17]:
abril2025 = formato_df(df_original)
abril2025

['h01_v01', 'h02_v02', 'h03_v03', 'h04_v04', 'h05_v05', 'h06_v06', 'h07_v07', 'h08_v08', 'h09_v09', 'h10_v10', 'h11_v11', 'h12_v12', 'h13_v13', 'h14_v14', 'h15_v15', 'h16_v16', 'h17_v17', 'h18_v18', 'h19_v19', 'h20_v20', 'h21_v21', 'h22_v22', 'h23_v23', 'h24_v24']

,provincia,municipio,estacion,magnitud,punto_muestreo,fecha,hora,valor,validacion,id_medida
0,28,102,1,1,28102001_1_38,2025-4-1,h01,4,V,28102001_1_38_2025-4-1_h01_V
1,28,102,1,6,28102001_6_48,2025-4-1,h01,"0,3",V,28102001_6_48_2025-4-1_h01_V
2,28,102,1,7,28102001_7_8,2025-4-1,h01,1,V,28102001_7_8_2025-4-1_h01_V
3,28,102,1,8,28102001_8_8,2025-4-1,h01,4,V,28102001_8_8_2025-4-1_h01_V
4,28,102,1,10,28102001_10_49,2025-4-1,h01,9,V,28102001_10_49_2025-4-1_h01_V
...,...,...,...,...,...,...,...,...,...,...
8683,28,92,5,7,28092005_7_8,2025-4-2,h24,2,V,28092005_7_8_2025-4-2_h24_V
8684,28,92,5,8,28092005_8_8,2025-4-2,h24,2,V,28092005_8_8_2025-4-2_h24_V
8685,28,92,5,10,28092005_10_49,2025-4-2,h24,3,V,28092005_10_49_2025-4-2_h24_V
8686,28,92,5,12,28092005_12_8,2025-4-2,h24,5,V,28092005_12_8_2025-4-2_h24_V
8687,28,92,5,14,28092005_14_6,2025-4-2,h24,81,V,28092005_14_6_2025-4-2_h24_V